/*
   FILE: patch_widgets.sql
   PURPOSE: Add tables for Chat Widgets and Conversations + Permissions
*/

-- 1. Create Widgets Table
IF OBJECT_ID('iam.Widgets', 'U') IS NULL
CREATE TABLE iam.Widgets (
    WidgetKey BIGINT IDENTITY(1,1) NOT NULL,
    WidgetId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    
    WorkspaceKey BIGINT NOT NULL,
    Name NVARCHAR(120) NOT NULL,
    Status TINYINT NOT NULL DEFAULT 1, -- 1=Enabled, 2=Disabled
    
    AllowedDomains NVARCHAR(MAX) NOT NULL, -- JSON array
    Theme NVARCHAR(MAX) NOT NULL, -- JSON object
    
    CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    RowVer ROWVERSION,
    
    CONSTRAINT PK_Widgets PRIMARY KEY CLUSTERED (WidgetKey),
    CONSTRAINT UQ_Widgets_WidgetId UNIQUE (WidgetId),
    CONSTRAINT FK_Widgets_Workspace 
        FOREIGN KEY (WorkspaceKey) REFERENCES iam.Workspaces(WorkspaceKey)
);

CREATE INDEX IX_Widgets_WorkspaceKey ON iam.Widgets(WorkspaceKey);
GO

-- 2. Create WidgetConversations Table
IF OBJECT_ID('iam.WidgetConversations', 'U') IS NULL
CREATE TABLE iam.WidgetConversations (
    ConversationKey BIGINT IDENTITY(1,1) NOT NULL,
    ConversationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    
    WidgetKey BIGINT NOT NULL,
    VisitorId NVARCHAR(80) NOT NULL, -- generated by widget
    Status TINYINT NOT NULL DEFAULT 1, -- 1=Open, 2=Closed
    
    CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    
    CONSTRAINT PK_WidgetConversations PRIMARY KEY CLUSTERED (ConversationKey),
    CONSTRAINT UQ_WidgetConversations_ConversationId UNIQUE (ConversationId),
    CONSTRAINT FK_WidgetConversations_Widget
        FOREIGN KEY (WidgetKey) REFERENCES iam.Widgets(WidgetKey)
);

CREATE INDEX IX_WidgetConversations_Lookup 
ON iam.WidgetConversations(WidgetKey, VisitorId, Status);
GO

-- 3. Create WidgetMessages Table
IF OBJECT_ID('iam.WidgetMessages', 'U') IS NULL
CREATE TABLE iam.WidgetMessages (
    MessageKey BIGINT IDENTITY(1,1) NOT NULL,
    MessageId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
    
    ConversationKey BIGINT NOT NULL,
    SenderType TINYINT NOT NULL, -- 1=Visitor, 2=Agent, 3=System
    Content NVARCHAR(MAX) NOT NULL,
    
    CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    
    CONSTRAINT PK_WidgetMessages PRIMARY KEY CLUSTERED (MessageKey),
    CONSTRAINT FK_WidgetMessages_Conversation
        FOREIGN KEY (ConversationKey) REFERENCES iam.WidgetConversations(ConversationKey)
);

CREATE INDEX IX_WidgetMessages_Conversation
ON iam.WidgetMessages(ConversationKey, CreatedAt);
GO

-- 4. Seed Permissions
IF NOT EXISTS (SELECT 1 FROM iam.Permissions WHERE Code = 'widget.read')
    INSERT INTO iam.Permissions (Code, Resource, Action) VALUES ('widget.read', 'widget', 'read');

IF NOT EXISTS (SELECT 1 FROM iam.Permissions WHERE Code = 'widget.manage')
    INSERT INTO iam.Permissions (Code, Resource, Action) VALUES ('widget.manage', 'widget', 'manage');
GO
